// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace project_user.Models;

public partial class UserData
{
    public int Id { get; set; }

    public string IdentificationNumber { get; set; }

    public string FullName { get; set; }

    public string Email { get; set; }

    public short Status { get; set; }
}