// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using project_user.Models;

namespace project_user.Data;

public partial class userManagementContext : DbContext
{
    public userManagementContext(DbContextOptions<userManagementContext> options)
        : base(options)
    {
    }

    public virtual DbSet<UserData> UserData { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<UserData>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__userData__3213E83F053132AB");

            entity.ToTable("userData");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.Email)
                .IsRequired()
                .HasMaxLength(150)
                .HasColumnName("email");
            entity.Property(e => e.FullName)
                .IsRequired()
                .HasMaxLength(200)
                .HasColumnName("fullName");
            entity.Property(e => e.IdentificationNumber)
                .IsRequired()
                .HasMaxLength(20)
                .HasColumnName("identificationNumber");
            entity.Property(e => e.Status)
                .HasDefaultValue((short)1)
                .HasColumnName("status");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}