// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace workItem.Models;

/// <summary>
/// Modelo de entidad que representa un elemento de trabajo o tarea.
/// Almacena la información completa de tareas que se asignan a usuarios.
/// </summary>
public partial class WorkItem
{
    /// <summary>Identificador único del elemento de trabajo en la base de datos</summary>
    public int Id { get; set; }

    /// <summary>Título o nombre del elemento de trabajo (campo obligatorio)</summary>
    public string Title { get; set; }

    /// <summary>Descripción detallada del elemento de trabajo (opcional)</summary>
    public string Description { get; set; }

    /// <summary>Estado del elemento (1 = activo, 0 = inactivo o completado)</summary>
    public short Status { get; set; }

    /// <summary>Fecha en la que vence o debe completarse el elemento de trabajo</summary>
    public DateTime DueDate { get; set; }

    /// <summary>Prioridad del elemento de trabajo (valor numérico)</summary>
    public int Priority { get; set; }

    /// <summary>Identificador del usuario a quien está asignado este elemento de trabajo</summary>
    public int? AssignedUserId { get; set; }

    /// <summary>Fecha y hora en la que fue creado el elemento de trabajo</summary>
    public DateTime CreatedDate { get; set; }
}