// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace workItem.Models;

public partial class WorkItem
{
    public int Id { get; set; }

    public string Title { get; set; }

    public string Description { get; set; }

    public short Status { get; set; }

    public DateTime DueDate { get; set; }

    public int Priority { get; set; }

    public string AssignedUserName { get; set; }

    public DateTime CreatedDate { get; set; }
}